---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build
        run: |
          docker build -t builder .
          docker run --rm -v $PWD/dist:/dist -e TRAVIS_BRANCH=${GITHUB_REF##*/} builder
