---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      artifact_file: dist/*
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build
        run: |
          docker build -t builder .
      - name: Run
        run: |
          docker run --rm -v $PWD/dist:/dist -e BRANCH_NAME=${GITHUB_REF##*/} builder
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.artifact_file }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
